package io.craigmiller160.authserver.exception

class NotFoundException(msg: String, cause: Throwable? = null) : RuntimeException(msg, cause)
